### ISSUE TITLE
lyrics not showing?

### ISSUE THREAD

**Issue by tjw0lf** [linuxdeepin/deepin-music#77]
I'm I missing something lyrics are not showing and words? how do you get them to show

**Comment by tjw0lf** [comment]
@BLumia ?

**Comment by BLumia** [comment]
I don't have environment which can run the current released deepin-music, but if you means you would like to use the lyrics from internet feature, you may need to build the related plugin by yourself (which just got comment out in https://github.com/linuxdeepin/deepin-music/commit/903b7f7a65df87c397bc464bb88c0ae6e0772c65 ).

**Comment by tjw0lf** [comment]
OK i uncommitted that in the file . I get this error @BLumia 

`../../../src/music-player/core/player.cpp:32:10: fatal error: DRecentManager: No such file or directory
 #include <DRecentManager>
          ^~~~~~~~~~~~~~~~
compilation terminated.
Makefile:1411: recipe for target 'player.o' failed
make[2]: *** [player.o] Error 1
make[2]: Leaving directory '/home/tj/deepin-music/build/src/music-player'
Makefile:135: recipe for target 'sub-music-player-make_first-ordered' failed
make[1]: *** [sub-music-player-make_first-ordered] Error 2
make[1]: Leaving directory '/home/tj/deepin-music/build/src'
Makefile:46: recipe for target 'sub-src-make_first-ordered' failed
make: *** [sub-src-make_first-ordered] Error 2
`

**Comment by BLumia** [comment]
Did you got all build depts installed? if not, please consider install all build detps first.

Since you didn't tell us your environment, assume you are using Deepin distro, you can uncomment the `deb-src` line inside `/etc/apt/sources.list` and do an `apt update`, then you can install all build depts by using `apt build-dep <package-name-here>`.

**Comment by tjw0lf** [comment]
How do i build snap package? @BLumia 

I was trying to build it on Ubuntu 18.04 but it doesn't build...

It works on Ubuntu 19.04 and 19.10.

**Comment by BLumia** [comment]
Sorry I don't know much about how to create a snap package :(

**Comment by tjw0lf** [comment]
OK Thanks @BLumia
